name: Manhunt
version: 0.2.0
description: Manhunt, track players with a compass!
authors: [Rit2, Akameki]
main: me.akameki.manhunt.Main
api-version: 1.16
commands:
  tracker:
    aliases: [track]
    description: Gives yourself a compass that tracks specified player
    usage: Syntax error! /<command> <player>