name: Manhunt
version: 0.0.3
authors: [Rit2, Akameki]
main: me.akameki.manhunt.Main
api-version: 1.16
commands:
  tracker:
    description: Gives user a compass that tracks specified player
    usage: /tracker <player>